version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/bookstore
      - JWT_SECRET=
      - JWT_EXPIRES_IN=24h
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: